[package]
name = "dll_injector"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["handleapi", "libloaderapi", "memoryapi", "minwindef", "processthreadsapi", "psapi", "synchapi", "timeapi", "tlhelp32"] }
